### ISSUE TITLE
Adding French-Canadian Keyboard to the build

### ISSUE THREAD

**Issue by JSChasle** [abesnier/docker-guacamole#23] opened 2023-07-31 20:52 UTC
Would it be possible to add the French-Canadian Keyboard to the build (Someone did and their docker does not work anymore?)

https://github.com/kavenr/guacamole-server/commit/962b48fae4d6ea9f5a447b34e93fc26b9d3c30d3

Thanks

**Comment by abesnier** [comment] 2023-08-05 12:10
Hi, sorry, I thought I had replied already.

Indeed, the code was merged with the 1.4 branch a while back, but I have to check to see if it is incorporated in 1.5.x.

For reference, the issue is with the upstream package, but I'll try to find why it is not present anymore, and if needed, raise a PR.

Cheers
Antoine

**Comment by abesnier** [comment] 2023-08-07 08:15
I had a better look at the PR. The keymap in question was added to the RDP protocol, on the guacamole server side. And items are created in the translation files for the Guacamole Client web app for fr_ca. But indeed, nothing is shown when trying to create or edit a RDP connection.

So I'll keep investigating, to see if the issue is with the way I build my images, or it is a bug with Guacamole client.

I'll keep you informed.

**Comment by abesnier** [comment] 2023-08-07 09:16
It's definitely missing from the official releases, so I've asked when it will be implemented.

https://lists.apache.org/thread/4wxwrf2mzd3rok3slgwq2yjfm0bmnbr1

**Comment by abesnier** [comment] 2023-08-07 13:02
The Guacamole dev replied that it will be implemented in the next release (1.6.0, not 1.5.4 that will soon be released apparently).

There two solutions for now:

- when building the image, I could git clone the guacamole-client repo, and build it, but that would make the image grow by a quite a lot (I already did some tests, it would almost double in size)
- I could build the client outside docker, but that would break the traceability of the webapp.

If you really need it, I could create a specific tag.

**Comment by JSChasle** [comment] 2023-08-07 13:14
Thanks you so much for all your help. If it is not to much trouble and you can make it a specific tag I would really appreciate it. and once again thanks so much for helping with this issue :)

**Comment by JSChasle** [comment] 2023-08-07 13:34
I am using your latest release from docker docker pull abesnier/guacamole:latest and whatever is the easiest for you. I will rebuilt the docker with what you will provide me. Am really gratefull for your time and help :)

**Comment by abesnier** [comment] 2023-08-07 14:04
Ostie de tabarnak, t'es tu pas un beggar toi! (sorry, I had too! Love from France!)

i forgot to ask which architecture (amd64 or arm)?

**Comment by JSChasle** [comment] 2023-08-07 15:28
Yeah perfect for amd64 :). Merci beaucoup! plein d'amour du Québec :)

**Comment by JSChasle** [comment] 2023-08-07 20:14
Thank you so much, everything works perfectly :)

**Closed** 2023-08-08 06:44 UTC
Labels: upstream
